// Code generated by typecfg-gen. DO NOT EDIT.

package typecfg

// ParityConfigBinder implements GeneratedBinder[ParityConfig].
type ParityConfigBinder struct{}

func (ParityConfigBinder) BindGenerated(raw map[string]any) (*ParityConfig, map[string]struct{}, []*FieldError) {
	cfg := &ParityConfig{}
	setFields := map[string]struct{}{}
	var errs []*FieldError
	if v, ok := Lookup(raw, "name"); ok {
		cfg.Name = AsString(v)
		setFields["name"] = struct{}{}
	} else {
		cfg.Name = "anon"
		setFields["name"] = struct{}{}
	}
	if v, ok := Lookup(raw, "enabled"); ok {
		n, err := ParseBool(AsString(v))
		if err != nil {
			errs = append(errs, NewBindTypeError("enabled", "enabled", "bool", false, err))
		} else {
			cfg.Enabled = n
			setFields["enabled"] = struct{}{}
		}
	} else {
		n, err := ParseBool("true")
		if err != nil {
			errs = append(errs, NewDefaultError("enabled", "true", false, err))
		} else {
			cfg.Enabled = n
			setFields["enabled"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "count"); ok {
		n, err := ParseInt(AsString(v), 64)
		if err != nil {
			errs = append(errs, NewBindTypeError("count", "count", "int", false, err))
		} else {
			cfg.Count = int(n)
			setFields["count"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "ratio"); ok {
		n, err := ParseFloat(AsString(v), 64)
		if err != nil {
			errs = append(errs, NewBindTypeError("ratio", "ratio", "float64", false, err))
		} else {
			cfg.Ratio = n
			setFields["ratio"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "timeout"); ok {
		n, err := ParseDuration(AsString(v))
		if err != nil {
			errs = append(errs, NewBindTypeError("timeout", "timeout", "time.Duration", false, err))
		} else {
			cfg.Timeout = n
			setFields["timeout"] = struct{}{}
		}
	} else {
		n, err := ParseDuration("1s")
		if err != nil {
			errs = append(errs, NewDefaultError("timeout", "1s", false, err))
		} else {
			cfg.Timeout = n
			setFields["timeout"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "start"); ok {
		n, err := ParseTime(AsString(v), "")
		if err != nil {
			errs = append(errs, NewBindTypeError("start", "start", "time.Time", false, err))
		} else {
			cfg.Start = n
			setFields["start"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "day"); ok {
		n, err := ParseTime(AsString(v), "2006-01-02")
		if err != nil {
			errs = append(errs, NewBindTypeError("day", "day", "time.Time", false, err))
		} else {
			cfg.Day = n
			setFields["day"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "tags"); ok {
		n, err := CoerceStringSlice(v)
		if err != nil {
			errs = append(errs, NewBindTypeError("tags", "tags", "[]string", false, err))
		} else {
			cfg.Tags = n
			setFields["tags"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "ports"); ok {
		n, err := CoerceIntSlice(v)
		if err != nil {
			errs = append(errs, NewBindTypeError("ports", "ports", "[]int", false, err))
		} else {
			cfg.Ports = n
			setFields["ports"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "rates"); ok {
		n, err := CoerceFloat64Slice(v)
		if err != nil {
			errs = append(errs, NewBindTypeError("rates", "rates", "[]float64", false, err))
		} else {
			cfg.Rates = n
			setFields["rates"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "labels"); ok {
		n, err := CoerceStringMap(v)
		if err != nil {
			errs = append(errs, NewBindTypeError("labels", "labels", "map[string]string", false, err))
		} else {
			cfg.Labels = n
			setFields["labels"] = struct{}{}
		}
	}
	if v, ok := Lookup(raw, "mode"); ok {
		cfg.Mode = AsString(v)
		setFields["mode"] = struct{}{}
	}
	if v, ok := Lookup(raw, "code"); ok {
		cfg.Code = AsString(v)
		setFields["code"] = struct{}{}
	}
	if v, ok := Lookup(raw, "home"); ok {
		cfg.Home = AsString(v)
		setFields["home"] = struct{}{}
	}
	if v, ok := Lookup(raw, "email"); ok {
		cfg.Email = AsString(v)
		setFields["email"] = struct{}{}
	}
	if v, ok := Lookup(raw, "token"); ok {
		cfg.Token = AsString(v)
		setFields["token"] = struct{}{}
	}
	{
		nested, _ := Lookup(raw, "server")
		var nestedMap map[string]any
		if m, ok := nested.(map[string]any); ok {
			nestedMap = m
		}
		if v, ok := Lookup(nestedMap, "host"); ok {
			cfg.Server.Host = AsString(v)
			setFields["server.host"] = struct{}{}
		} else {
			cfg.Server.Host = "0.0.0.0"
			setFields["server.host"] = struct{}{}
		}
		if v, ok := Lookup(nestedMap, "port"); ok {
			n, err := ParseInt(AsString(v), 64)
			if err != nil {
				errs = append(errs, NewBindTypeError("server.port", "port", "int", false, err))
			} else {
				cfg.Server.Port = int(n)
				setFields["server.port"] = struct{}{}
			}
		}
	}
	return cfg, setFields, errs
}

func (ParityConfigBinder) ValidateGenerated(cfg *ParityConfig, setFields map[string]struct{}, raw map[string]any) []*FieldError {
	var errs []*FieldError
	if reason := CheckRule("required", "", "count", "count", cfg.Count, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "count", Tag: "required",
			Sources: FieldSources("count", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("min", "0", "count", "count", cfg.Count, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "count", Tag: "min",
			Sources: FieldSources("count", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("max", "1000", "count", "count", cfg.Count, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "count", Tag: "max",
			Sources: FieldSources("count", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("gt", "-1", "count", "count", cfg.Count, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "count", Tag: "gt",
			Sources: FieldSources("count", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("lt", "1001", "count", "count", cfg.Count, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "count", Tag: "lt",
			Sources: FieldSources("count", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("oneof", "dev prod", "mode", "mode", cfg.Mode, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "mode", Tag: "oneof",
			Sources: FieldSources("mode", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("regexp", "^[A-Z]+$", "code", "code", cfg.Code, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "code", Tag: "regexp",
			Sources: FieldSources("code", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("url", "", "home", "home", cfg.Home, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "home", Tag: "url",
			Sources: FieldSources("home", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("email", "", "email", "email", cfg.Email, setFields, raw, false); reason != "" {
		errs = append(errs, &FieldError{
			Field: "email", Tag: "email",
			Sources: FieldSources("email", ""),
			Reason:  reason,
		})
	}
	if reason := CheckRule("oneof", "a b c", "token", "token", cfg.Token, setFields, raw, true); reason != "" {
		errs = append(errs, &FieldError{
			Field: "token", Tag: "oneof",
			Sources: FieldSources("token", ""),
			Reason:  reason,
		})
	}
	{
		nestedRaw := NestedRaw(raw, "server")
		if reason := CheckRule("required", "", "server.port", "port", cfg.Server.Port, setFields, nestedRaw, false); reason != "" {
			errs = append(errs, &FieldError{
				Field: "server.port", Tag: "required",
				Sources: FieldSources("port", ""),
				Reason:  reason,
			})
		}
		if reason := CheckRule("min", "1", "server.port", "port", cfg.Server.Port, setFields, nestedRaw, false); reason != "" {
			errs = append(errs, &FieldError{
				Field: "server.port", Tag: "min",
				Sources: FieldSources("port", ""),
				Reason:  reason,
			})
		}
		if reason := CheckRule("max", "65535", "server.port", "port", cfg.Server.Port, setFields, nestedRaw, false); reason != "" {
			errs = append(errs, &FieldError{
				Field: "server.port", Tag: "max",
				Sources: FieldSources("port", ""),
				Reason:  reason,
			})
		}
	}
	if v, ok := any(cfg).(Validator); ok {
		if err := v.Validate(); err != nil {
			errs = append(errs, &FieldError{Field: "<struct>", Tag: "Validate()", Reason: err.Error()})
		}
	}
	return errs
}
