// Code generated by typecfg-gen. DO NOT EDIT.

package main

import (
	"github.com/sinashahoveisi/typecfg"
)

// ConfigBinder implements typecfg.GeneratedBinder[Config].
type ConfigBinder struct{}

func (ConfigBinder) BindGenerated(raw map[string]any) (*Config, map[string]struct{}, []*typecfg.FieldError) {
	cfg := &Config{}
	setFields := map[string]struct{}{}
	var errs []*typecfg.FieldError
	if v, ok := typecfg.Lookup(raw, "port"); ok {
		n, err := typecfg.ParseInt(typecfg.AsString(v), 64)
		if err != nil {
			errs = append(errs, typecfg.NewBindTypeError("port", "port", "int", false, err))
		} else {
			cfg.Port = int(n)
			setFields["port"] = struct{}{}
		}
	}
	return cfg, setFields, errs
}

func (ConfigBinder) ValidateGenerated(cfg *Config, setFields map[string]struct{}, raw map[string]any) []*typecfg.FieldError {
	var errs []*typecfg.FieldError
	if reason := typecfg.CheckRule("required", "", "port", "port", cfg.Port, setFields, raw, false); reason != "" {
		errs = append(errs, &typecfg.FieldError{
			Field: "port", Tag: "required",
			Sources: typecfg.FieldSources("port", ""),
			Reason: reason,
		})
	}
	if reason := typecfg.CheckRule("min", "1", "port", "port", cfg.Port, setFields, raw, false); reason != "" {
		errs = append(errs, &typecfg.FieldError{
			Field: "port", Tag: "min",
			Sources: typecfg.FieldSources("port", ""),
			Reason: reason,
		})
	}
	if v, ok := any(cfg).(typecfg.Validator); ok {
		if err := v.Validate(); err != nil {
			errs = append(errs, &typecfg.FieldError{Field: "<struct>", Tag: "Validate()", Reason: err.Error()})
		}
	}
	return errs
}
