// Code generated by typecfg-gen. DO NOT EDIT.

package integration

import (
	"github.com/sinashahoveisi/typecfg"
)

// ServiceConfigBinder implements typecfg.GeneratedBinder[ServiceConfig].
type ServiceConfigBinder struct{}

func (ServiceConfigBinder) BindGenerated(raw map[string]any) (*ServiceConfig, map[string]struct{}, []*typecfg.FieldError) {
	cfg := &ServiceConfig{}
	setFields := map[string]struct{}{}
	var errs []*typecfg.FieldError
	{
		nested, _ := typecfg.Lookup(raw, "server")
		var nestedMap map[string]any
		if m, ok := nested.(map[string]any); ok {
			nestedMap = m
		}
		if v, ok := typecfg.Lookup(nestedMap, "host"); ok {
			cfg.Server.Host = typecfg.AsString(v)
			setFields["server.host"] = struct{}{}
		} else {
			cfg.Server.Host = "0.0.0.0"
			setFields["server.host"] = struct{}{}
		}
		if v, ok := typecfg.Lookup(nestedMap, "port"); ok {
			n, err := typecfg.ParseInt(typecfg.AsString(v), 64)
			if err != nil {
				errs = append(errs, typecfg.NewBindTypeError("server.port", "port", "int", false, err))
			} else {
				cfg.Server.Port = int(n)
				setFields["server.port"] = struct{}{}
			}
		}
	}
	if v, ok := typecfg.Lookup(raw, "features"); ok {
		n, err := typecfg.CoerceStringSlice(v)
		if err != nil {
			errs = append(errs, typecfg.NewBindTypeError("features", "features", "[]string", false, err))
		} else {
			cfg.Features = n
			setFields["features"] = struct{}{}
		}
	}
	if v, ok := typecfg.Lookup(raw, "labels"); ok {
		n, err := typecfg.CoerceStringMap(v)
		if err != nil {
			errs = append(errs, typecfg.NewBindTypeError("labels", "labels", "map[string]string", false, err))
		} else {
			cfg.Labels = n
			setFields["labels"] = struct{}{}
		}
	}
	if v, ok := typecfg.Lookup(raw, "started_at"); ok {
		n, err := typecfg.ParseTime(typecfg.AsString(v), "")
		if err != nil {
			errs = append(errs, typecfg.NewBindTypeError("started_at", "started_at", "time.Time", false, err))
		} else {
			cfg.StartedAt = n
			setFields["started_at"] = struct{}{}
		}
	}
	if v, ok := typecfg.Lookup(raw, "api_key"); ok {
		cfg.APIKey = typecfg.AsString(v)
		setFields["api_key"] = struct{}{}
	}
	if v, ok := typecfg.Lookup(raw, "log_level"); ok {
		cfg.LogLevel = typecfg.AsString(v)
		setFields["log_level"] = struct{}{}
	} else {
		cfg.LogLevel = "info"
		setFields["log_level"] = struct{}{}
	}
	return cfg, setFields, errs
}

func (ServiceConfigBinder) ValidateGenerated(cfg *ServiceConfig, setFields map[string]struct{}, raw map[string]any) []*typecfg.FieldError {
	var errs []*typecfg.FieldError
	{
		nestedRaw := typecfg.NestedRaw(raw, "server")
		if reason := typecfg.CheckRule("required", "", "server.port", "port", cfg.Server.Port, setFields, nestedRaw, false); reason != "" {
			errs = append(errs, &typecfg.FieldError{
				Field: "server.port", Tag: "required",
				Sources: typecfg.FieldSources("port", ""),
				Reason:  reason,
			})
		}
		if reason := typecfg.CheckRule("min", "1", "server.port", "port", cfg.Server.Port, setFields, nestedRaw, false); reason != "" {
			errs = append(errs, &typecfg.FieldError{
				Field: "server.port", Tag: "min",
				Sources: typecfg.FieldSources("port", ""),
				Reason:  reason,
			})
		}
		if reason := typecfg.CheckRule("max", "65535", "server.port", "port", cfg.Server.Port, setFields, nestedRaw, false); reason != "" {
			errs = append(errs, &typecfg.FieldError{
				Field: "server.port", Tag: "max",
				Sources: typecfg.FieldSources("port", ""),
				Reason:  reason,
			})
		}
	}
	if reason := typecfg.CheckRule("required", "", "api_key", "api_key", cfg.APIKey, setFields, raw, true); reason != "" {
		errs = append(errs, &typecfg.FieldError{
			Field: "api_key", Tag: "required",
			Sources: typecfg.FieldSources("api_key", ""),
			Reason:  reason,
		})
	}
	if reason := typecfg.CheckRule("oneof", "debug info warn error", "log_level", "log_level", cfg.LogLevel, setFields, raw, false); reason != "" {
		errs = append(errs, &typecfg.FieldError{
			Field: "log_level", Tag: "oneof",
			Sources: typecfg.FieldSources("log_level", ""),
			Reason:  reason,
		})
	}
	if v, ok := any(cfg).(typecfg.Validator); ok {
		if err := v.Validate(); err != nil {
			errs = append(errs, &typecfg.FieldError{Field: "<struct>", Tag: "Validate()", Reason: err.Error()})
		}
	}
	return errs
}
