package main

import (
	"bytes"
	"fmt"
	"strings"
)

func emit(opts Options, fields []fieldInfo) ([]byte, error) {
	self := opts.PackageName == "typecfg"
	pfx := "typecfg."
	if self {
		pfx = ""
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by typecfg-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.PackageName)

	imports := collectImports(self)
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, im := range imports {
			fmt.Fprintf(&b, "\t%q\n", im)
		}
		b.WriteString(")\n\n")
	}

	binder := opts.TypeName + "Binder"
	fmt.Fprintf(&b, "// %s implements %sGeneratedBinder[%s].\n", binder, pfx, opts.TypeName)
	fmt.Fprintf(&b, "type %s struct{}\n\n", binder)

	fmt.Fprintf(&b, "func (%s) BindGenerated(raw map[string]any) (*%s, map[string]struct{}, []*%sFieldError) {\n", binder, opts.TypeName, pfx)
	fmt.Fprintf(&b, "\tcfg := &%s{}\n", opts.TypeName)
	b.WriteString("\tsetFields := map[string]struct{}{}\n")
	fmt.Fprintf(&b, "\tvar errs []*%sFieldError\n", pfx)
	emitBindFields(&b, fields, "raw", pfx)
	b.WriteString("\treturn cfg, setFields, errs\n}\n\n")

	fmt.Fprintf(&b, "func (%s) ValidateGenerated(cfg *%s, setFields map[string]struct{}, raw map[string]any) []*%sFieldError {\n", binder, opts.TypeName, pfx)
	fmt.Fprintf(&b, "\tvar errs []*%sFieldError\n", pfx)
	emitValidateFields(&b, fields, "raw", "cfg", pfx)
	fmt.Fprintf(&b, "\tif v, ok := any(cfg).(%sValidator); ok {\n", pfx)
	b.WriteString("\t\tif err := v.Validate(); err != nil {\n")
	fmt.Fprintf(&b, "\t\t\terrs = append(errs, &%sFieldError{Field: \"<struct>\", Tag: \"Validate()\", Reason: err.Error()})\n", pfx)
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn errs\n}\n")

	return b.Bytes(), nil
}

func collectImports(self bool) []string {
	var out []string
	if !self {
		out = append(out, "github.com/sinashahoveisi/typecfg")
	}
	return out
}

func emitBindFields(b *bytes.Buffer, fields []fieldInfo, rawExpr, pfx string) {
	for _, f := range fields {
		if f.Kind == kindStruct {
			fmt.Fprintf(b, "\t{\n")
			fmt.Fprintf(b, "\t\tnested, _ := %sLookup(%s, %q)\n", pfx, rawExpr, f.CfgKey)
			fmt.Fprintf(b, "\t\tvar nestedMap map[string]any\n")
			fmt.Fprintf(b, "\t\tif m, ok := nested.(map[string]any); ok {\n")
			fmt.Fprintf(b, "\t\t\tnestedMap = m\n")
			fmt.Fprintf(b, "\t\t}\n")
			emitBindFields(b, f.Nested, "nestedMap", pfx)
			fmt.Fprintf(b, "\t}\n")
			continue
		}
		emitBindScalar(b, f, rawExpr, pfx)
	}
}

func emitBindScalar(b *bytes.Buffer, f fieldInfo, rawExpr, pfx string) {
	secret := fmt.Sprintf("%v", f.Secret)
	fmt.Fprintf(b, "\tif v, ok := %sLookup(%s, %q); ok {\n", pfx, rawExpr, f.CfgKey)
	emitAssignFromRaw(b, f, "v", pfx, secret)
	if f.HasDefault {
		fmt.Fprintf(b, "\t} else {\n")
		emitAssignFromDefault(b, f, pfx, secret)
		fmt.Fprintf(b, "\t}\n")
	} else {
		fmt.Fprintf(b, "\t}\n")
	}
}

func emitAssignFromRaw(b *bytes.Buffer, f fieldInfo, rawVar, pfx, secret string) {
	dst := "cfg." + f.AccessPath
	switch f.Kind {
	case kindString:
		fmt.Fprintf(b, "\t\t%s = %sAsString(%s)\n", dst, pfx, rawVar)
		fmt.Fprintf(b, "\t\tsetFields[%q] = struct{}{}\n", f.FieldPath)
	case kindBool:
		fmt.Fprintf(b, "\t\tn, err := %sParseBool(%sAsString(%s))\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindInt:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "int(n)", dst)
	case kindInt8:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "int8(n)", dst)
	case kindInt16:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "int16(n)", dst)
	case kindInt32:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "int32(n)", dst)
	case kindInt64:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindUint:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "uint(n)", dst)
	case kindUint8:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "uint8(n)", dst)
	case kindUint16:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "uint16(n)", dst)
	case kindUint32:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "uint32(n)", dst)
	case kindUint64:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindFloat32:
		fmt.Fprintf(b, "\t\tn, err := %sParseFloat(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "float32(n)", dst)
	case kindFloat64:
		fmt.Fprintf(b, "\t\tn, err := %sParseFloat(%sAsString(%s), 64)\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindDuration:
		fmt.Fprintf(b, "\t\tn, err := %sParseDuration(%sAsString(%s))\n", pfx, pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindTime:
		layout := f.Layout
		fmt.Fprintf(b, "\t\tn, err := %sParseTime(%sAsString(%s), %q)\n", pfx, pfx, rawVar, layout)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindStringMap:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceStringMap(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindStringSlice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceStringSlice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindIntSlice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceIntSlice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindInt8Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt8Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindInt16Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt16Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindInt32Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt32Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindInt64Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt64Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindUintSlice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUintSlice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindUint8Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint8Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindUint16Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint16Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindUint32Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint32Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindUint64Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint64Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindFloat32Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceFloat32Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	case kindFloat64Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceFloat64Slice(%s)\n", pfx, rawVar)
		emitBindErrCheck(b, f, pfx, secret, "n", dst)
	default:
		fmt.Fprintf(b, "\t\t_ = %s // unsupported\n", rawVar)
	}
}

func emitBindErrCheck(b *bytes.Buffer, f fieldInfo, pfx, secret, expr, dst string) {
	fmt.Fprintf(b, "\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\terrs = append(errs, %sNewBindTypeError(%q, %q, %q, %s, err))\n", pfx, f.FieldPath, f.CfgKey, f.TypeName, secret)
	fmt.Fprintf(b, "\t\t} else {\n")
	fmt.Fprintf(b, "\t\t\t%s = %s\n", dst, expr)
	fmt.Fprintf(b, "\t\t\tsetFields[%q] = struct{}{}\n", f.FieldPath)
	fmt.Fprintf(b, "\t\t}\n")
}

func emitAssignFromDefault(b *bytes.Buffer, f fieldInfo, pfx, secret string) {
	dst := "cfg." + f.AccessPath
	def := f.Default
	switch f.Kind {
	case kindString:
		fmt.Fprintf(b, "\t\t%s = %q\n", dst, def)
		fmt.Fprintf(b, "\t\tsetFields[%q] = struct{}{}\n", f.FieldPath)
	case kindBool:
		fmt.Fprintf(b, "\t\tn, err := %sParseBool(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindInt:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "int(n)", dst)
	case kindInt8:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "int8(n)", dst)
	case kindInt16:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "int16(n)", dst)
	case kindInt32:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "int32(n)", dst)
	case kindInt64:
		fmt.Fprintf(b, "\t\tn, err := %sParseInt(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindUint:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "uint(n)", dst)
	case kindUint8:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "uint8(n)", dst)
	case kindUint16:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "uint16(n)", dst)
	case kindUint32:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "uint32(n)", dst)
	case kindUint64:
		fmt.Fprintf(b, "\t\tn, err := %sParseUint(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindFloat32:
		fmt.Fprintf(b, "\t\tn, err := %sParseFloat(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "float32(n)", dst)
	case kindFloat64:
		fmt.Fprintf(b, "\t\tn, err := %sParseFloat(%q, 64)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindDuration:
		fmt.Fprintf(b, "\t\tn, err := %sParseDuration(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindTime:
		fmt.Fprintf(b, "\t\tn, err := %sParseTime(%q, %q)\n", pfx, def, f.Layout)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindStringMap:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceStringMap(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindStringSlice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceStringSlice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindIntSlice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceIntSlice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindInt8Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt8Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindInt16Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt16Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindInt32Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt32Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindInt64Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceInt64Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindUintSlice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUintSlice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindUint8Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint8Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindUint16Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint16Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindUint32Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint32Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindUint64Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceUint64Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindFloat32Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceFloat32Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	case kindFloat64Slice:
		fmt.Fprintf(b, "\t\tn, err := %sCoerceFloat64Slice(%q)\n", pfx, def)
		emitDefaultErrCheck(b, f, pfx, secret, def, "n", dst)
	}
}

func emitDefaultErrCheck(b *bytes.Buffer, f fieldInfo, pfx, secret, def, expr, dst string) {
	fmt.Fprintf(b, "\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\terrs = append(errs, %sNewDefaultError(%q, %q, %s, err))\n", pfx, f.FieldPath, def, secret)
	fmt.Fprintf(b, "\t\t} else {\n")
	fmt.Fprintf(b, "\t\t\t%s = %s\n", dst, expr)
	fmt.Fprintf(b, "\t\t\tsetFields[%q] = struct{}{}\n", f.FieldPath)
	fmt.Fprintf(b, "\t\t}\n")
}

func emitValidateFields(b *bytes.Buffer, fields []fieldInfo, rawExpr, cfgExpr, pfx string) {
	for _, f := range fields {
		if f.Kind == kindStruct && hasValidate(f.Nested) {
			fmt.Fprintf(b, "\t{\n")
			fmt.Fprintf(b, "\t\tnestedRaw := %sNestedRaw(%s, %q)\n", pfx, rawExpr, f.CfgKey)
			emitValidateFields(b, f.Nested, "nestedRaw", cfgExpr, pfx)
			fmt.Fprintf(b, "\t}\n")
		}
		if f.Validate == "" {
			continue
		}
		for _, rule := range strings.Split(f.Validate, ",") {
			rule = strings.TrimSpace(rule)
			if rule == "" {
				continue
			}
			name, arg, _ := strings.Cut(rule, "=")
			secret := fmt.Sprintf("%v", f.Secret)
			fmt.Fprintf(b, "\tif reason := %sCheckRule(%q, %q, %q, %q, %s.%s, setFields, %s, %s); reason != \"\" {\n",
				pfx, name, arg, f.FieldPath, f.CfgKey, cfgExpr, f.AccessPath, rawExpr, secret)
			fmt.Fprintf(b, "\t\terrs = append(errs, &%sFieldError{\n", pfx)
			fmt.Fprintf(b, "\t\t\tField: %q, Tag: %q,\n", f.FieldPath, name)
			fmt.Fprintf(b, "\t\t\tSources: %sFieldSources(%q, %q),\n", pfx, f.CfgKey, f.EnvTag)
			fmt.Fprintf(b, "\t\t\tReason: reason,\n")
			fmt.Fprintf(b, "\t\t})\n")
			fmt.Fprintf(b, "\t}\n")
		}
	}
}

func hasValidate(fields []fieldInfo) bool {
	for _, f := range fields {
		if f.Validate != "" {
			return true
		}
		if f.Kind == kindStruct && hasValidate(f.Nested) {
			return true
		}
	}
	return false
}
