package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate_SupportedCompiles(t *testing.T) {
	dir := t.TempDir()
	in := filepath.Join(dir, "config.go")
	out := filepath.Join(dir, "config_gen.go")
	src := `package sample

import "time"

type Config struct {
	Host string        ` + "`cfg:\"host\" default:\"localhost\"`" + `
	Port int           ` + "`cfg:\"port\" validate:\"required,min=1\"`" + `
	Start time.Time    ` + "`cfg:\"start\"`" + `
	Tags []string      ` + "`cfg:\"tags\"`" + `
	Meta map[string]string ` + "`cfg:\"meta\"`" + `
	Nested struct {
		Name string ` + "`cfg:\"name\"`" + `
	} ` + "`cfg:\"nested\"`" + `
}
`
	if err := os.WriteFile(in, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	code, err := Generate(Options{TypeName: "Config", InputPath: in, PackageName: "sample"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.Contains(string(code), "Code generated by typecfg-gen. DO NOT EDIT.") {
		t.Fatal("missing generated file marker")
	}
	if !strings.Contains(string(code), "type ConfigBinder struct{}") {
		t.Fatal("missing binder type")
	}
	if err := os.WriteFile(out, code, 0o644); err != nil {
		t.Fatal(err)
	}
	// Also need a tiny go.mod that replaces typecfg to the repo root.
	repoRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	mod := "module sample\n\ngo 1.22\n\nrequire github.com/sinashahoveisi/typecfg v0.0.0\n\nreplace github.com/sinashahoveisi/typecfg => " + filepath.ToSlash(repoRoot) + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(mod), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "build", ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if outBytes, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build generated package: %v\n%s", err, outBytes)
	}
}

func TestGenerate_UnsupportedFieldFails(t *testing.T) {
	dir := t.TempDir()
	in := filepath.Join(dir, "bad.go")
	src := `package bad

type Config struct {
	Ch chan int ` + "`cfg:\"ch\"`" + `
}
`
	if err := os.WriteFile(in, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := Generate(Options{TypeName: "Config", InputPath: in, PackageName: "bad"})
	if err == nil {
		t.Fatal("expected generation error for chan field")
	}
	msg := err.Error()
	if !strings.Contains(msg, "ch") {
		t.Errorf("error should name field, got %q", msg)
	}
	if !strings.Contains(msg, "unsupported") {
		t.Errorf("error should say unsupported, got %q", msg)
	}
}

func TestGenerate_PointerFieldFails(t *testing.T) {
	dir := t.TempDir()
	in := filepath.Join(dir, "ptr.go")
	src := `package ptr

type Inner struct { N int ` + "`cfg:\"n\"`" + ` }
type Config struct {
	Inner *Inner ` + "`cfg:\"inner\"`" + `
}
`
	if err := os.WriteFile(in, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := Generate(Options{TypeName: "Config", InputPath: in, PackageName: "ptr"})
	if err == nil {
		t.Fatal("expected generation error for pointer field")
	}
	if !strings.Contains(err.Error(), "pointer") {
		t.Errorf("want pointer error, got %q", err)
	}
}

func TestGenerate_SubprocessCLI(t *testing.T) {
	dir := t.TempDir()
	in := filepath.Join(dir, "config.go")
	out := filepath.Join(dir, "config_gen.go")
	src := `package cli

type Config struct {
	Port int ` + "`cfg:\"port\" validate:\"required\"`" + `
}
`
	if err := os.WriteFile(in, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "run", ".", "-type", "Config", "-in", in, "-out", out, "-package", "cli")
	cmd.Dir = "."
	if outBytes, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go run typecfg-gen: %v\n%s", err, outBytes)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "ConfigBinder") {
		t.Fatalf("unexpected output:\n%s", data)
	}
}
